### ISSUE TITLE
not able to retrieve data

### ISSUE THREAD

**Issue by Saripalle** [roserustowicz/crop-type-mapping#117]
I tried to run "gsutil -m cp -r gs://es262-croptype/Tanzania/* ./data" and pull the data, but after setting up my bucket, I get a permission error 

```
AccessDeniedException: 403 xxxx@gmail.com does not have storage.objects.list access to es262-croptype.

```

**Comment by Saripalle** [comment]
Also, I looked at starting the download from google storage and it says "Bucket not available. Either it does not exist or you do not have access. Click "Browse" to verify the bucket name. If you can browse to the bucket, you need to ask a bucket owner for access." . I am sure I am missing something in this process. any pointers?

**Comment by roserustowicz** [comment]
@Saripalle there are permissions restrictions on the current dataset, but it will be uploaded to the Stanford Digital Libraries shortly -- will update you once it's ready.

**Comment by roserustowicz** [comment]
Following up here, the datasets are now available in Radiant Earth's ML Hub. The links are listed in the main project README.
