### ISSUE TITLE
train / val / test split

### ISSUE THREAD

**Issue by VSainteuf** [roserustowicz/crop-type-mapping#119]
Hi!
I'd like to know If you could share the precise train/val/test split used in the paper?
Because of rare classes a random split is not an option and the `data_split.py` script in the repo seems to be using input files that are not provided with the dataset.
So if you still have a split file handy that would be really helpful.
Thanks in advance!

**Comment by roserustowicz** [comment]
@VSainteuf the dataset split files are now available here: https://github.com/roserustowicz/crop-type-mapping/tree/master/dataset_splits

Note that these correspond to the 64x64 tiles saved on Radiant Earth's ML Hub. To create the exact inputs used in the models in this repo, and reported in the accompanying paper, these 64x64 tiles were further broken down into 32x32 tiles. 

Thank you for your interest!
