### ISSUE TITLE
Bands order

### ISSUE THREAD

**Issue by Sina-Mohammadi** [roserustowicz/crop-type-mapping#121]
Hello. I want to use your dataset in my project, but first I need to know the order of the spectral bands in your data. Is the following the correct order of the 10 bands (channels) in your data? 
Blue, Green, Red, Red Edge 1, Red Edge 2, Red Edge 3, NIR,  Red Edge 4, SWIR 1, SWIR 2

**Comment by roserustowicz** [comment]
Hi, here are the band orders for the different image products:
```
s1_bands = {'0': 'VV', '1': 'VH', '2': 'VH/VV', '3': 'DOY'}
s2_bands = {'0': 'Blue', '1': 'Green', '2': 'Red', '3': 'Red Edge 1', '4': 'Red Edge 2', '5': 'Red Edge 3', 
            '6': 'NIR', '7': 'Red Edge 4', '8': 'SWIR 1', '9': 'SWIR 2', '10': 'Clouds', '11': 'DOY'}
planet_bands = {'0': 'Blue', '1': 'Green', '2': 'Red', '3': 'NIR', '4': 'DOY'}
```
