### ISSUE TITLE
CM_LABELS definition

### ISSUE THREAD

**Issue by XiaoleiQinn** [roserustowicz/crop-type-mapping#123]
Thank you for sharing the code!  When I display these dataset, value 0 should be the background. I wonder if CM_LABELS should start with the value 1 in constants.py, corresponding to the CROPS definition?

**Comment by 1flyingpig** [comment]
I also have the same question. I would like to know what text labels correspond to different numeric labels in Ghana and South Sudan. Have you solved this problem? Can we share some information?

**Comment by roserustowicz** [comment]
These values should be used as are defined in the `constants.py` file:

```
CM_LABELS = { 'ghana': [0, 1, 2, 3], 
              'southsudan': [0, 1, 2, 3], 
              'tanzania': [0, 1, 2, 3, 4],
              'germany': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] }

CROPS = { 'ghana': ['groundnut', 'maize', 'rice', 'soya bean'], 
          'southsudan': ['sorghum', 'maize', 'rice', 'groundnut'], 
          'tanzania': ['maize', 'beans', 'sunflower', 'chickpeas', 'wheat'],
          'germany': ['sugar beet', 'summer oat', 'meadow', 'rapeseed', 'hop', 'winter spelt', 
                      'winter triticale', 'beans', 'peas', 'potato', 'soybeans', 'asparagus', 
                      'winter wheat', 'winter barley', 'winter rye', 'summer barley', 'maize']}
```

**Comment by 1flyingpig** [comment]
> These values should used as are defined in the `constants.py` file:
> 
> ```
> CM_LABELS = { 'ghana': [0, 1, 2, 3], 
>               'southsudan': [0, 1, 2, 3], 
>               'tanzania': [0, 1, 2, 3, 4],
>               'germany': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] }
> 
> CROPS = { 'ghana': ['groundnut', 'maize', 'rice', 'soya bean'], 
>           'southsudan': ['sorghum', 'maize', 'rice', 'groundnut'], 
>           'tanzania': ['maize', 'beans', 'sunflower', 'chickpeas', 'wheat'],
>           'germany': ['sugar beet', 'summer oat', 'meadow', 'rapeseed', 'hop', 'winter spelt', 
>                       'winter triticale', 'beans', 'peas', 'potato', 'soybeans', 'asparagus', 
>                       'winter wheat', 'winter barley', 'winter rye', 'summer barley', 'maize']}
> ```

I saw this information in Constant.py, but maybe it wasn't useful to me, maybe I wasn't clear, because I was reading the.npz file in truth directly as lable, but I found that the number labels here ranged from 0 to 24, It is not the 0-4 number label you provided, so I have the above question, I wonder if you can solve this problem, thank you very much.

**Comment by yurujaja** [comment]
Same issue here. The provided truth data seems to not match the description. Can you elaborate this more?
